// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PenCheck.Data;

namespace PenCheck.Migrations
{
    [DbContext(typeof(ParticipantsContext))]
    [Migration("20210201075104_AddPlan")]
    partial class AddPlan
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("PenCheck.Models.Participant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SSN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SelectedPlanId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SelectedPlanId");

                    b.ToTable("Participant");
                });

            modelBuilder.Entity("PenCheck.Models.Plan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Plan");
                });

            modelBuilder.Entity("PenCheck.Models.Participant", b =>
                {
                    b.HasOne("PenCheck.Models.Plan", "SelectedPlan")
                        .WithMany("Participants")
                        .HasForeignKey("SelectedPlanId");

                    b.Navigation("SelectedPlan");
                });

            modelBuilder.Entity("PenCheck.Models.Plan", b =>
                {
                    b.Navigation("Participants");
                });
#pragma warning restore 612, 618
        }
    }
}
